### ISSUE TITLE
Name on the login page appears as 'Django Administration'

### ISSUE THREAD

**Issue by gaurav08suri** [parth-gudhka/MHT-Portal#8]
Name on the portal appears as 'Django administration'.
This needs to be changed to something like 'MHT-Portal'.

**Comment by parth-gudhka** [comment]
Gauravbhai,
Tried the 2nd link you sent: https://www.packtpub.com/books/content/creating-administration-interface-django
But it didn't work. I think somewhere in settings.py, we will have to tell Django to use the local templates and not the default Django templates.
@sidharthshah Please, can you have a look at this.

**Comment by gaurav08suri** [comment]
You are correct......Need to add the path to local templates, to the tuple
TEMPLATE_DIR in settings.py

**Comment by gaurav08suri** [comment]
Typo ... it should be TEMPLATE_DIRS

**Comment by gaurav08suri** [comment]
Is this ticket fixed with the new changes commited ?

**Comment by parth-gudhka** [comment]
Thank you for the suggestions! That is in fact the right way to do it. (BASE_DIR + '/templates',)
Fixed it using the latest commit, but forgot to add the issue no., otherwise would have directly closed the issue.
